# System dependant tasks
- name: Install Git
  import_tasks: debian.yml
  when: ansible_facts['os_family'] == 'Debian'
- import_tasks: archlinux.yml
  when: ansible_facts['os_family'] == 'Archlinux'
# Common tasks
# configure .gitconfig file
# core.autocrlf
- name: core.autocrlf
  ini_file:
    create: true
    path: ~/.gitconfig
    section: core
    option: autocrlf
    value: "input"
# core.pager
- name: core.pager
  ini_file:
    path: ~/.gitconfig
    section: core
    option: pager
    value: more
# color.diff
- name: color.diff
  ini_file:
    path: ~/.gitconfig
    section: color
    option: diff
    value: auto
# color.status
- name: color.status
  ini_file:
    path: ~/.gitconfig
    section: color
    option: status
    value: auto
# color.branch
- name: color.branch
  ini_file:
    path: ~/.gitconfig
    section: color
    option: branch
    value: auto
# alias.ci
- name: alias.ci
  ini_file:
    path: ~/.gitconfig
    section: alias
    option: ci
    value: commit
# alias.co      
- name: alias.co      
  ini_file:
    path: ~/.gitconfig
    section: alias
    option: co
    value: checkout
# alias.st      
- name: alias.st      
  ini_file:
    path: ~/.gitconfig
    section: alias
    option: st
    value: status
# alias.br
- name: alias.br
  ini_file:
    path: ~/.gitconfig
    section: alias
    option: br
    value: branch
# alias.spull 
- name: alias.spull 
  ini_file:
    path: ~/.gitconfig
    section: alias
    option: spull
    value: "!git stash && git pull && git stash pop"
# alias.oops
- name: alias.oops
  ini_file:
    path: ~/.gitconfig
    section: alias
    option: oops
    value: commit --amend --no-edit
# alias.lg
- name: alias.lg
  ini_file:
    path: ~/.gitconfig
    section: alias
    option: lg
    value: log --graph --date=relative --pretty=tformat:'%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%an %ad)%Creset' 
# pull.rebase
- name: pull.rebase
  ini_file:
    path: ~/.gitconfig
    section: pull
    option: rebase
    value: preserve
# push.default
- name: push.default
  ini_file:
    path: ~/.gitconfig
    section: push
    option: default
    value: upstream
# tag.sort
- name: tag.sort
  ini_file:
    path: ~/.gitconfig
    section: tag
    option: sort
    value: version:refname


